#Considering example data, show different List functions (e.g. append(), del, remove(), sort(),
#insert(), pop(), extend() etc.) in python  
 
x=[]
print("\nUsing append we create a list:") 
x.append(3)
x.append(2)
x.append(1)
x.append(6) 
x.append(7) 
x.append(5) 
print(x)
print("\nWe insert 4 at index 3:") 
x.insert(3,4)
print(x)
print("\nWe delete data at index 3:") 
del x[3]
print(x)
print("\nWe append 78:") 
x.append(78)
print(x)
print("\nWe remove 78:")
x.remove(78)
print(x)
print("\nWe Sort the list:")
x.sort()
print(x)
print("\nWe pop index 2:")
x.pop(2)
print(x)
print("\nWe use extend and add a list with a list:")
x.extend([7, 8, (2, 3)])
print(x)
print("\nWe splice the list:")
print(x[1:5])
print(x[:5]) 
print(x[3:])
print(x[-6:-2]) 
print(x[::-1]) 
print("\nWe can sort a list using a key, here we use the length of the words:")
b = ['saw', 'small', 'He', 'foxes', 'six']
print(b)
b.sort(key=len)
print(b)
 
